
import type { Metadata } from "next";
import "./globals.css";
import { RecoilRoot } from "recoil";
import App from "./app";

export const metadata: Metadata = {
  title: "Learning English",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-[100vw] h-[100svh]">
        <App>{children}</App>
      </body>
    </html>
  );
}
